runtime: python37
entrypoint: gunicorn -b :$PORT lmnop_project.wsgi

handlers:
- url: /lmnop
  static_dir: /lmnop/static

- url: /.*
  script: auto


env_variables:
  TRAVELER_PW: sdfg324g


beta_settings:
  cloud_sql_instances: lmnop-273410:us-central1:lmnop-db