# Generated by Django 3.0.5 on 2020-05-13 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.CharField(choices=[('Poor', 'Poor Show'), ('Average', 'Average Show'), ('Good', 'Good Show'), ('Very Good', 'Very Good Show'), ('Excellent', 'Excellent Show')], default='Good', max_length=15),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favArtist', models.CharField(blank=True, max_length=200)),
                ('favShow', models.CharField(blank=True, max_length=200)),
                ('favVenue', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
