# Generated by Django 3.0.5 on 2020-05-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_auto_20200424_1302'),
        ('lmn', '0002_auto_20200501_1544'),
        ('lmn', '0002_auto_20200423_1726'),
    ]

    operations = [
    ]
