# Generated by Django 2.1.11 on 2020-05-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_auto_20200407_1855'),
        ('lmn', '0002_auto_20200501_1544'),
        ('lmn', '0002_auto_20200408_1307'),
    ]

    operations = [
    ]
