# Generated by Django 2.1.11 on 2020-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20200512_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rating',
            field=models.CharField(choices=[('Poor', 'Poor Show'), ('Average', 'Average Show'), ('Good', 'Good Show'), ('Very Good', 'Very Good Show'), ('Excellent', 'Excellent Show')], default='Good', max_length=15),
        ),
    ]
