runtime: python37
entrypoint: gunicorn -b :$PORT lmnop_project.wsgi

handlers:
- url: /static
  static_dir: /static/




env_variables:
  TRAVELER_PW: sdfg324g


beta_settings:
  cloud_sql_instances: lmnop-273410:us-central1:lmnop-db